id: A0E848EB2
title: Guru Yoga of the Guru Mahāmuni
type: translation
pechas:
- I901E665A
- I6DC43514
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:12:51.686326
  last_modified_at: 2023-01-04 12:12:51.686333
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I901E665A/9BC6: 84B3
  I6DC43514/881E: 84B3
